

eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka-0
  client:
    service-url:
      defaultZone: http://eureka-0.eureka-service.default.svc.cluster.local:8761/eureka

spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:Mynepal150*@atlas-cluster.ap3ory9.mongodb.net/?retryWrites=true&w=majority
      host: atlas-cluster.ap3ory9.mongodb.net
      port: 27017
      database: orderdb
      repositories:
        enabled: true